routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'HomeController@home')->name('home');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/posts/tags/{tag}', 'BlogPostTagController@index')->name('post-tags');

Route::resource('posts', 'PostController');
Route::resource('posts.comments', 'PostCommentController')->only(['store']);

Route::resource('users', 'UserController')->only(['show', 'edit', 'update']);
Route::resource('users.comments', 'UserCommentsController')->only(['store']);

Auth::routes();

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Contracts\CounterContract;
use App\Events\BlogPostPosted;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

use App\Models\BlogPost;
use App\Http\Requests\StorePost;
use App\Models\Image;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{

    private $counter;

    public function __construct(CounterContract $counter)
    {
        $this->middleware('auth')->except(['index', 'show']);
        $this->counter = $counter;
    }

    public function index()
    {
        return view('home', [
            'posts' => BlogPost::latest()->withCount('comment')->get(),
            'mostCommented' => BlogPost::mostCommented()->take(5)->get(),
        ]);
    }

    public function create()
    {
        return view('posts.create');
    }

    public function store(StorePost $request)
    {
        $validateData = $request->validated();
        $validateData['user_id'] = $request->user()->id;
        $blogPost = BlogPost::create($validateData);

        if ($request->hasFile('thumbnail')) {
            $path = $request->file('thumbnail')->store('thumbnails');
            $blogPost->image()->save(Image::make(['path' => $path]));
        }

        event(new BlogPostPosted($blogPost));

        $request->session()->flash('status', 'Post successfully created !!');

        return redirect()->route('posts.show', ['post' => $blogPost->id]);
    }

    public function show($id)
    {
        $post = Cache::tags(['blog-post'])->remember("blog-post-{$id}", now()->addSeconds(60), function () use ($id) {
            return BlogPost::with('comment', 'tags', 'user', 'comment.user')->findOrFail($id);
        });

        // $counter = resolve(Counter::class);

        return view('posts.show', [
            'post' => $post,
            'counter' => $this->counter->increment("blog-post-{$id}", ['blog-post'])
        ]);
    }

    public function edit($id)
    {
        $post = BlogPost::findOrFail($id);
        $this->authorize('update', $post);

        return view('posts.edit', ['post' => $post]);
    }

    public function update(StorePost $request, $id)
    {
        $post = BlogPost::findOrFail($id);
        $this->authorize('update', $post);

        $validateData = $request->validated();
        $post->fill($validateData);

        if ($request->hasFile('thumbnail')) {
            $path = $request->file('thumbnail')->store('thumbnails');
            if ($post->image) {
                Storage::delete($post->image->path);
                $post->image->path = $path;
                $post->image->save();
            } else {
                $post->image()->save(Image::make(['path' => $path]));
            }
        }

        $post->save();
        $request->session()->flash('status', 'Post successfully updated!!');

        return redirect()->route('posts.show', ['post' => $post->id]);
    }

    public function destroy(Request $request, $id)
    {
        $post = BlogPost::findOrFail($id);
        $this->authorize('delete', $post);
        $post->delete();

        $request->session()->flash('status', 'Post successfully deleted!!');
        return redirect()->route('home');
    }

    private function userCount(int $id)
    {
        $sessionId = session()->getId();
        $counterKey = "blog-post-{$id}-counter";
        $userKey = "blog-post-{$id}-user";

        $users = Cache::tags(['blog-post'])->get($userKey, []);
        $userUpdate = [];
        $difference = 0;
        $now = now();

        foreach ($users as $session => $lastVisit) {
            if ($now->diffInMinutes($lastVisit) >= 1) {
                $difference--;
            } else {
                $userUpdate[$session] = $lastVisit;
            }
        }

        if (!array_key_exists($sessionId, $users) || $now->diffInMinutes($users[$sessionId]) >= 1) {
            $difference++;
        }

        $userUpdate[$sessionId] = $now;

        Cache::tags(['blog-post'])->forever($userKey, $userUpdate);
        if (!Cache::tags(['blog-post'])->has($counterKey)) {
            Cache::tags(['blog-post'])->forever($counterKey, 1);
        } else {
            Cache::tags(['blog-post'])->increment($counterKey, $difference);
        }
        return Cache::tags(['blog-post'])->get($counterKey);
    }
}

resources/views/contact.blade.php
@extends('layouts.app')

@section('title')
Contact
@endsection

@section('content')
<div class="container">
    <div class="jumbotron">
        <h1 class="display-3">Contact</h1>
        <p class="lead">Here is our contact page!</p>
        @can('home.contact')
            <hr class="my-2">
            <p>More info</p>
            <p class="lead">
                <a class="btn btn-primary btn-lg" href="Jumbo action link" role="button">Some Action</a>
            </p>
        @endcan
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('title')
Home
@endsection

@section('content')
<div class="container">
    <div class="row">
        {{-- posts --}}
        <div class="col-9">
            <div class="row justify-content-start">
                @forelse ($posts as $post)
                <div class="col-md-4 d-flex p-2">
                    <div class="card flex-fill">
                        <div class="card-header">
                            <a href="{{ route('posts.show', ['post' => $post->id]) }}" style="color: black;">
                                {{ $post->title }}
                            </a>
                        </div>

                        <div class="card-body">
                            <p>{{ $post->description }}</p>
                        </div>
                        {{-- tags --}}
                        <div class="card-body d-flex align-items-end">
                            <x-tags :tags="$post->tags" />
                        </div>
                        {{-- card footer --}}
                        <div class="card-footer d-flex justify-content-between align-items-center">
                            <span class="card-subtitle text-muted">
                                @if ($post->comment_count)
                                    {{ $post->comment_count }} comments
                                @else
                                    No comments yet!
                                @endif
                            </span>
                            <span class="card-subtitle text-muted">
                                <a href="{{ route('users.show', ['user'=>$post->user->id]) }}">{{ $post->user->name }}</a>
                            </span>
                        </div>
                    </div>
                </div>
                @empty
                    <p>No Post!!</p>
                @endforelse
            </div>
        </div>
        {{-- Activity section --}}
        <div class="col-3 p-2">
            @include('posts._activity')
        </div>
    </div>
</div>
@endsection