routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'HomeController@home')->name('home');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/posts/tags/{tag}', 'BlogPostTagController@index')->name('post-tags');

Route::resource('posts', 'PostController');
Route::resource('posts.comments', 'PostCommentController')->only(['store']);

Route::resource('users', 'UserController')->only(['show', 'edit', 'update']);
Route::resource('users.comments', 'UserCommentsController')->only(['store']);

Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function blogPost()
    {
        return $this->hasMany(BlogPost::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function commentsOn()
    {
        return $this->morphMany(Comment::class, 'commentable')->latest();
    }

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }

    // Local scopes
    public function scopeMostActiveUser($query)
    {
        return $this->withCount('blogPost')->orderBy('blog_post_count', 'desc');
    }

    public function scopeMostActiveLastMonth($query)
    {
        return $query->withCount(['blogPost' => function (Builder $query) {
            return $query->whereBetween(static::CREATED_AT, [now()->subMonths(1), now()]);
        }])->having('blog_post_count', '>=', 2)->orderBy('blog_post_count', 'desc');
    }

    public function scopeThatHasCommentedOnPost($query, BlogPost $post)
    {
        return $query->whereHas('comments', function ($query) use ($post) {
            return $query->where('commentable_id', '=', $post->id)
                ->where('commentable_type', '=', BlogPost::class);
        });
    }

    public function scopeThatIsAdmin($query)
    {
        return $query->where('is_admin', true);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdateUser;
use App\Models\Image;
use App\Models\User;
use App\Services\Counter;
use Illuminate\Http\Request;

class UserController extends Controller
{

    private $counter;

    public function __construct(Counter $counter)
    {
        $this->middleware('auth');
        $this->authorizeResource(User::class, 'user');
        $this->counter = $counter;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUser $request, User $user)
    {
        if ($request->hasFile('avatar')) {
            $path = $request->file('avatar')->store('avatars');

            if ($user->image) {
                $user->image->path = $path;
                $user->image->save();
            } else {
                $user->image()->save(Image::make(['path' => $path]));
            }
        }

        return redirect()->back()->withStatus('Profile updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title')
Edit {{ $user->name }} Profile
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 d-flex p-2">
            <div class="card flex-fill">
                <div class="card-body">
                    <h4 class="card-title">Edit {{ $user->name }}</h4>
                    <form action="{{ route('users.update', ['user' => $user->id])}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                          <label for="name">Name</label>
                          <input type="text" name="name" id="name" class="form-control">
                        </div>
                        <div class="form-group">
                          <label for="avatar">Avatar</label>
                          <input type="file" class="form-control-file" name="avatar" id="avatar" />
                        </div>
                        <button type="submit" class="btn btn-primary btn-block mt-3">Update</button>
                    </form>
                    <x-errors />
                </div>
            </div>
        </div>
        <div class="col-md-4 d-flex p-2">
            <div class="card flex-fill align-items-center justify-content-center">
                @if (isset($user->image))
                    <img class="card-img" src="{{ $user->image->url() }}" alt="{{ $user->name }}">
                @else
                    <h5>No Avatar!!</h5>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('title')
{{ $user->name }} Profile
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 d-flex p-2">
            <div class="card flex-fill">
                <div class="card-body">
                    <h4 class="card-title">{{ $user->name }}</h4>
                    <p class="card-text">{{ $user->email }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 d-flex p-2">
            <div class="card flex-fill align-items-center justify-content-center">
                @if (isset($user->image))
                <img class="card-img" src="{{ $user->image->url() }}" alt="{{ $user->name }}">
                @else
                    <h5 class="align-middle">No Avatar!!</h5>
                @endif
            </div>
        </div>
    </div>

    {{-- comment section --}}
    <div class="row">
        <div class="col-md-12 d-flex p-2">
            <div class="card flex-fill">
                <div class="card-body">
                    <h4 class="card-title">Commets</h4>
                    <x-comment-form :route="route('users.comments.store', ['user' => $user->id])" />
                    <x-comment-list :comments="$user->commentsOn" />
                </div>
            </div>
        </div>
    </div>

</div>
@endsection