routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'HomeController@home')->name('home');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/posts/tags/{tag}', 'BlogPostTagController@index')->name('post-tags');

Route::resource('posts', 'PostController');
Route::resource('posts.comments', 'PostCommentController')->only(['store']);

Route::resource('users', 'UserController')->only(['show', 'edit', 'update']);
Route::resource('users.comments', 'UserCommentsController')->only(['store']);

Auth::routes();

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Contracts\CounterContract;
use App\Events\BlogPostPosted;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

use App\Models\BlogPost;
use App\Http\Requests\StorePost;
use App\Models\Image;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{

    private $counter;

    public function __construct(CounterContract $counter)
    {
        $this->middleware('auth')->except(['index', 'show']);
        $this->counter = $counter;
    }

    public function index()
    {
        return view('home', [
            'posts' => BlogPost::latest()->withCount('comment')->get(),
            'mostCommented' => BlogPost::mostCommented()->take(5)->get(),
        ]);
    }

    public function create()
    {
        return view('posts.create');
    }

    public function store(StorePost $request)
    {
        $validateData = $request->validated();
        $validateData['user_id'] = $request->user()->id;
        $blogPost = BlogPost::create($validateData);

        if ($request->hasFile('thumbnail')) {
            $path = $request->file('thumbnail')->store('thumbnails');
            $blogPost->image()->save(Image::make(['path' => $path]));
        }

        event(new BlogPostPosted($blogPost));

        $request->session()->flash('status', 'Post successfully created !!');

        return redirect()->route('posts.show', ['post' => $blogPost->id]);
    }

    public function show($id)
    {
        $post = Cache::tags(['blog-post'])->remember("blog-post-{$id}", now()->addSeconds(60), function () use ($id) {
            return BlogPost::with('comment', 'tags', 'user', 'comment.user')->findOrFail($id);
        });

        // $counter = resolve(Counter::class);

        return view('posts.show', [
            'post' => $post,
            'counter' => $this->counter->increment("blog-post-{$id}", ['blog-post'])
        ]);
    }

    public function edit($id)
    {
        $post = BlogPost::findOrFail($id);
        $this->authorize('update', $post);

        return view('posts.edit', ['post' => $post]);
    }

    public function update(StorePost $request, $id)
    {
        $post = BlogPost::findOrFail($id);
        $this->authorize('update', $post);

        $validateData = $request->validated();
        $post->fill($validateData);

        if ($request->hasFile('thumbnail')) {
            $path = $request->file('thumbnail')->store('thumbnails');
            if ($post->image) {
                Storage::delete($post->image->path);
                $post->image->path = $path;
                $post->image->save();
            } else {
                $post->image()->save(Image::make(['path' => $path]));
            }
        }

        $post->save();
        $request->session()->flash('status', 'Post successfully updated!!');

        return redirect()->route('posts.show', ['post' => $post->id]);
    }

    public function destroy(Request $request, $id)
    {
        $post = BlogPost::findOrFail($id);
        $this->authorize('delete', $post);
        $post->delete();

        $request->session()->flash('status', 'Post successfully deleted!!');
        return redirect()->route('home');
    }

    private function userCount(int $id)
    {
        $sessionId = session()->getId();
        $counterKey = "blog-post-{$id}-counter";
        $userKey = "blog-post-{$id}-user";

        $users = Cache::tags(['blog-post'])->get($userKey, []);
        $userUpdate = [];
        $difference = 0;
        $now = now();

        foreach ($users as $session => $lastVisit) {
            if ($now->diffInMinutes($lastVisit) >= 1) {
                $difference--;
            } else {
                $userUpdate[$session] = $lastVisit;
            }
        }

        if (!array_key_exists($sessionId, $users) || $now->diffInMinutes($users[$sessionId]) >= 1) {
            $difference++;
        }

        $userUpdate[$sessionId] = $now;

        Cache::tags(['blog-post'])->forever($userKey, $userUpdate);
        if (!Cache::tags(['blog-post'])->has($counterKey)) {
            Cache::tags(['blog-post'])->forever($counterKey, 1);
        } else {
            Cache::tags(['blog-post'])->increment($counterKey, $difference);
        }
        return Cache::tags(['blog-post'])->get($counterKey);
    }
}

resources/views/posts/_activity.blade.php
{{-- the most commented posts --}}
{{-- <x-card title="Most Commented Posts" :items="collect($mostCommented)->pluck('title', 'comment_count')" /> --}}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Most Commented Posts</h4>
    </div>
    <ul class="list-group list-group-flush">
        @foreach ($mostCommented as $post)
            <li class="list-group-item">
                <a href="{{ route('posts.show', ['post' => $post->id]) }}" style="color: black;">
                    {{ $post->title }}
                </a>
                <span class="text-muted">({{ $post->comment_count }})</span>
            </li>
        @endforeach
    </ul>
</div>
{{-- the most active user --}}
<div class="card mt-3">
    <div class="card-body">
        <h4 class="card-title">Most Active Users</h4>
    </div>
    <ul class="list-group list-group-flush">
        @foreach ($mostActive as $user)
            <li class="list-group-item">
                {{ $user->name }}
                <span class="text-muted">({{ $user->blog_post_count }})</span>
            </li>
        @endforeach
    </ul>
</div>
{{-- the most active user in last month --}}
<div class="card mt-3">
    <div class="card-body">
        <h4 class="card-title">Most Active User Last Month</h4>
    </div>
    <ul class="list-group list-group-flush">
        @foreach ($mostActiveLastMonth as $user)
            <li class="list-group-item">
                {{ $user->name }}
                <span class="text-muted">({{ $user->blog_post_count }})</span>
            </li>
        @endforeach
    </ul>
</div>
            

resources/views/posts/_form.blade.php
<div class="form-group">
    <label for="title">Title</label>
    <input type="text" name="title" id="title" class="form-control" value="{{ old('title', $post->title ?? null) }}">
</div>
<div class="form-group">
    <label for="description">Descritpion</label>
    <textarea class="form-control" name="description" id="description" rows="5">
        {{ old('description', $post->description ?? null) }}
    </textarea>
</div>
<div class="form-group">
    <label for="thumbnail">Thumbnail</label>
    <input type="file" class="form-control-file" name="thumbnail" id="thumbnail">
</div>
<x-errors />

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('title')
Create
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Create Post</a></div>

                <div class="card-body">
                    <form action="{{ route('posts.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @include('posts._form')
                        <button type="submit" class="btn btn-primary btn-block">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('title')
Edit
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Edit Post</a></div>

                <div class="card-body">
                    <form action="{{ route('posts.update', ['post' => $post->id]) }}" method="post"
                        enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        @include('posts._form')
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('title')
Blog
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                {{-- card header --}}
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4>{{ $post->title }}</h4>
                    <div>
                        <x-added :date="$post->created_at" :name="$post->user->name" :userId="$post->user->id"/>
                        {{-- badge for new posts --}}
                        <x-badge type="success" :show="now()->diffInMinutes($post->created_at) < 30">
                            New
                        </x-badge>
                    </div>
                </div>
                <div class="card-body">
                    {{-- description --}}
                    <p>{{ $post->description }}</p>
                    <div class="d-flex justify-content-between">
                        <span class="text-muted">Read by {{ $counter }} people</span>
                        <span>
                            <x-tags :tags="$post->tags" /></span>
                    </div>
                    <hr>
                    {{-- comment section --}}
                    <x-comment-form :route="route('posts.comments.store', ['post' => $post->id])" />
                    <x-comment-list :comments="$post->comment" />
                </div>
                {{-- card footer --}}
                @auth
                <div class="card-footer d-flex justify-content-between align-items-center">
                    @can('update', $post)
                    <a class="btn btn-outline-primary col-sm-2" href="{{ route('posts.edit', ['post' => $post]) }}"
                        role="button">Edit</a>
                    @endcan
                    @can('delete', $post)
                    <form action="{{ route('posts.destroy', ['post' => $post->id]) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                    </form>
                    @endcan
                </div>
                @endauth
            </div>
        </div>
        @if ($post->image)
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img" src="{{ $post->image->url() }}">
                </div>
            </div>
        @endif
    </div>
</div>
@endsection